version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "1212:1212"
    volumes:
      - ../api_specification/v1-api.yaml:/api/api.yaml
    environment:
      - SWAGGER_JSON=/api/api.yaml
