services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bdui
    ports:
      - "5432:5432"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "1212:8080"
    volumes:
      - ./api_specification:/api
    environment:
      - SWAGGER_JSON=/api/bdui.yaml