spring:
  jpa:
    show-sql: true

kafka:
  bootstrap-servers:
    - "localhost:9092"

outbox:
  screen:
    updated:
      name: "outbox_screen_updated"
    created:
      name: "outbox_screen_created"